# Generated by Django 2.2 on 2020-08-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_comment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
    ]
