# Generated by Django 2.2 on 2020-07-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
    ]
