# Generated by Django 2.2 on 2020-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='posts', through='content.PostTag', to='content.Tag', verbose_name='tags'),
        ),
    ]
