# Generated by Django 2.2 on 2020-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200731_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='content.PostTag', to='content.Tag', verbose_name='tags'),
        ),
    ]
