# Generated by Django 2.2 on 2020-08-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200801_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
