# Generated by Django 2.2 on 2020-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200801_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttag',
            old_name='tag',
            new_name='tagged',
        ),
    ]
