# Generated by Django 2.2 on 2020-08-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200801_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttag',
            old_name='tagged',
            new_name='tag',
        ),
    ]
