# Generated by Django 2.2 on 2020-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200822_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='content.PostTag', to='content.Tag', verbose_name='tags'),
        ),
    ]
